Algoritmo "atividae2"

Var
 n1, n2, n3 : inteiro


Inicio
 escreval("imforme um numero")
 leia(n1)
 escreval("imforme um numero")
 leia(n2)
 escreval("imforme um numero")
 
 leia(n3)
 
 se n1> n2 entao
 se n1< n3 entao
        escreval(n3, " e o maior")
 fimse
senao


 se n2 > n3 entao
    escreval (n2, "e o maior")
    senao
     escreval(n3, "e o maior")
     
     fimse
 fimse

 
Fimalgoritmo