Algoritmo "atividade2"

Var

nascimento,atual,mes,dia,futuro,res1, res2: inteiro


Inicio
atual<-2023
futuro<-2050
escreva("informe o ano do seu nascimento:")
leia(nascimento)
escreval("informe o mes do seu nasciemnto")
leia(mes)
escreval("informe o dia do seu nascimento")
leia(dia)
res1<-atual-nascimento
res2<-futuro-nascimento
escreval("atualmente voce possui", res1," anos")
escreval("no ano de 2050 voce vai ter", res2," anos")





Fimalgoritmo